name: Build and release beta

on:
  workflow_dispatch:
    inputs:
      git-repo:
        description: Git repo (Optional, defaults to <your name>/aniyomi-extensions-tester
        required: false
      optimized-build:
        type: boolean
        description: Upload a optimized build
        required: false
        default: false
      git-branch:
        description: Git branch (optional, defaults to master)
        default: master
        required: false
      git-draft:
        type: boolean
        description: Create a draft release
        required: false
        default: false
env:
    REPO: ${{ github.event.inputs.git-repo }}
    TASK_NAME: shadowJar
    BUILD_DIR: server/build

jobs:
  build-tester:
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          set -x
          if [[ "$REPO" == "" ]]; then
            echo "REPO=${{ github.repository_owner }}/aniyomi-extensions-tester" >> $GITHUB_ENV
          fi
          if [[ "${{ github.event.inputs.optimized-build }}" == "true" ]]; then
            echo "TASK_NAME=optimizeShadowJar" >> $GITHUB_ENV
            echo "BUILD_DIR=$BUILD_DIR/min" >> $GITHUB_ENV
          fi

      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build the tester
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: :server:${{ env.TASK_NAME }}
          gradle-home-cache-cleanup: true
      
      - name: Upload beta
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ env.BUILD_DIR }}/*.jar"
          prerelease: false
          draft: ${{ github.event.inputs.git-draft }}
          verbose: true
          tag_name: beta
          overwrite: true          

